version: '3'
services:
  vehicle_api:
    image: xxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/py-fsk-playground/vehicle-api:${VERSION}
    container_name: vehicle-api
    build: ./python_flask_playground
    ports:
      - "8080:8080"
    expose:
      - "8080"
  vehicle-nginx:
    image: xxxxxxxx.dkr.ecr.ap-northeast-1.amazonaws.com/py-fsk-playground/vehicle-nginx:${VERSION}
    container_name: vehicle-nginx
    build: ./nginx
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - vehicle_api
